name: mobilehealthapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  webview_flutter: ^0.3.22+1
  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.4.5
  image_picker: ^0.6.7+4
  mlkit: ^0.15.1
  http: ^0.12.2
  provider: ^4.3.1
  fl_chart: ^0.11.0
  charts_flutter: ^0.9.0
  flutter_circular_chart: ^0.1.0
  google_nav_bar: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: OpenSans
      fonts:
         - asset: fonts/OpenSans-Regular.ttf
    - family: Spartan
      fonts:
         - asset: fonts/Spartan-Regular.ttf
  #         style: italic
  #    - family: Trajan Pro
  #       fonts:
  #        - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
